# Generated by Django 5.2.4 on 2025-07-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=30)),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('image', models.ImageField(blank=True, upload_to='images%Y%m%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='main.category', verbose_name='Категория')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='main.color', verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='SneakerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField()),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.size')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sneaker')),
            ],
        ),
        migrations.AddField(
            model_name='sneaker',
            name='sizes',
            field=models.ManyToManyField(related_name='sneakers', through='main.SneakerSize', to='main.size', verbose_name='Размер'),
        ),
    ]
