# Generated by Django 5.2.4 on 2025-08-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AddField(
            model_name='sneaker',
            name='brand',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='main.category'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='main.color'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='sizes',
            field=models.ManyToManyField(related_name='sneakers', through='main.SneakerSize', to='main.size'),
        ),
    ]
