# Generated by Django 5.2.5 on 2025-09-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brand_alter_sneaker_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Color'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
